[package]
name = "mair_minigames"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
once_cell = "1.19.0"
rand = "0.8.5"
ratatui = "0.26.1"
regex = "1.10.3"
